### ISSUE TITLE
Examples in resources/swagger would be nice

### ISSUE THREAD

**Issue by kolotyluk** [pjfanning/swagger-akka-http-sample#10]
Examples are always the best way to understand something as prose is usually full of ambiguity and other problems. Adding the swagger.json and/or swagger.yaml would be a good way to make this example more complete and useful.

**Comment by gerbrand** [comment]
Slightly related, I've extended the existing example to include a ui: https://github.com/pjfanning/swagger-akka-http-sample/pull/16 so if you run the example now you get a ui which hopefully makes the example easier to understand.

**Comment by pjfanning** [comment]
I put the swagger.json on README page.
