### ISSUE TITLE
Is there a way to put boolean query params as an optional parameters. Currently it seems I can just have boolean to be selected as either true or false.

### ISSUE THREAD

**Issue by mikip91** [pjfanning/swagger-akka-http-sample#11]
@pjfanning : Please respond as I have an urgent business requirement for passing null values for booleans and not to include it in url is value is null for boolean

**Comment by pjfanning** [comment]
Have you tried a case class with a param that has type `Option[Boolean]`?

**Comment by mikip91** [comment]
Hey there,

Yes I did try.

It does not allow me to specify null from swagger. The default value is
considered as true.

**Comment by pjfanning** [comment]
Do you know which of the following is happening?
* the swagger json that is generated incorrectly marks the field as required?
* the client misinterprets the swagger json and sends a value of `true` instead of `null`?
* the server-side code receives `null` but incorrectly interprets that as `Some(true)`?

Maybe, if you could provide a sample, it would be easier to check the problem.

**Comment by mikip91** [comment]
I think it's the first option.

There is not a way to select anything else apart from true or false in the
swagger page and hence the selection persists. Is there a way we could add
Null, True and false options so that when we pass null the query params can
be omitted?

**Comment by pjfanning** [comment]
You are using the swagger UI and it only offers true and false as options?

**Comment by pjfanning** [comment]
I added a branch to this git repo called `optional-boolean` and modified the addOptional web service to use booleans instead of ints.

Note the way that I had to annotate the Option[Boolean] because the inner type is erased by the compiler.

```
  // due to type erasure of inner types for scala.Option[T] when T is a primitive type like Int or Boolean,
  // the only way to ensure generated swagger doc has int/boolean type for number2 is to use an annotation
  case class AddOptionRequest(number: Boolean,
                              @Schema(required = false, implementation = classOf[Boolean]) number2: Option[Boolean] = None)
```

The generated swagger json is correct - in that, it treats the optional boolean as optional.

```
      "AddOptionRequest" : {
        "required" : [ "number" ],
        "type" : "object",
        "properties" : {
          "number" : {
            "type" : "boolean"
          },
          "number2" : {
            "type" : "boolean"
          }
        }
      }
```

**Comment by mikip91** [comment]
Thanks a lot. I will try that and will keep you posted.

**Comment by mikip91** [comment]
> You are using the swagger UI and it only offers true and false as options?

@pjfanning Yes!

**Comment by mikip91** [comment]
@pjfanning: We are still using swagger-akka-http version 1.1.0. Could you please post the optional-boolean changes for version 1.1.0. We are having a hard time upgrading the swagger-akka-http version to 2.0.4?

**Comment by pjfanning** [comment]
I created a 2nd branch `optional-boolean-1.5`

**Comment by mikip91** [comment]
@pjfanning: Thanks for reverting so quickly.

I was able to pull the changes in our code. However, our query still stands. The problem is:

I have a boolean field name discoverable which could have **true false or null**. So, if I select null the query params should not be passed at all. I still am not able to find a way to pass null thorough swagger-ui(v2.1.1). If you could please give me a pointer which would help?

**Comment by pjfanning** [comment]
I think you'll need to direct swagger-ui problems to the swagger-ui team

**Comment by mikip91** [comment]
Thanks @pjfanning. Got this sorted. Appreciate your help.
