### ISSUE TITLE
How can I access swagger UI

### ISSUE THREAD

**Issue by suyogchoudhari** [pjfanning/swagger-akka-http-sample#6]
I can see JSON of URIs with http://localhost:12345/api-docs/swagger.json
Where can I see swagger-ui? Can you please provide link?

**Comment by pjfanning** [comment]
http://petstore.swagger.io/

**Comment by suyogchoudhari** [comment]
I mean on localhost

**Comment by suyogchoudhari** [comment]
Got it. Never mind.
